name = "smart-qa-factory-app"
main = "src/worker.js"
compatibility_date = "2026-05-16"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "smartqa_prod"
database_id = ""d1_databases": [{
    "binding": "DB",
    "database_name": "smartqa_prod",
    "database_id": "9ebce5cc-ad72-46cb-b63e-8d61e11f510f"
 }]"

[[r2_buckets]]
binding = "DOC_BUCKET"
bucket_name = "smartqa-documents"
